httpTimeout: 600000
defaultSemverRangePrefix: ''
yarnPath: .yarn/releases/yarn-3.5.0.cjs
supportedArchitectures:
  os:
    - 'darwin'
    - 'linux'
    - 'win32'
  cpu:
    - 'x64'
    - 'x86'
    - 'arm'
    - 'ia32'
  libc:
    - 'glibc'
    - 'musl'
